# Generated by Django 3.2.6 on 2021-08-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(default='author', max_length=12)),
                ('pages', models.DecimalField(decimal_places=0, max_digits=4)),
                ('premiere', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
